### ISSUE TITLE
doc slash command mangles url

### ISSUE THREAD

**Issue by eMoss55** [matlab-discord/Matlab-Discord-Bot#18]
When the slash command version of doc is used to search, the url that MAT-Bot returns has the last seven characters repeated, causing the url not to be functional.
![image](https://user-images.githubusercontent.com/70984589/165362190-7756a4e3-597a-4d02-bb73-91d1e352b1fa.png)

The issue does not occur when using the original command (!doc)
![image](https://user-images.githubusercontent.com/70984589/165362427-3f5b41d3-936a-49f5-822d-5b55f757fe5b.png)

**Comment by Sam-Reinsel** [comment]
This appears to be fixed in the most recent version, though I'm not sure which commit fixed it. 
![image](https://github.com/matlab-discord/Matlab-Discord-Bot/assets/62652294/713593f7-6109-4355-adab-47e441976d85)

Closing for now because _hygiene!_
